services:
  mongodb:
    hostname: mongodb
    image: mongodb/mongodb-atlas-local
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - config:/data/configdb
    deploy:
      resources:
        limits:
          cpus: 6
          memory: 8G
        reservations:
          cpus: 2
          memory: 4G

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_INITDB_ROOT_USERNAME}:${MONGODB_INITDB_ROOT_PASSWORD}@mongodb:27017/admin
    ports:
      - 8081:8081
    depends_on:
      - mongodb
volumes:
  data:
  config:
