FROM postgres:latest

# Install necessary packages
RUN apt-get update && \
    apt-get install -y git build-essential postgresql-server-dev-all && \
    rm -rf /var/lib/apt/lists/*

# Clone and install pgvector
RUN git clone --branch v0.5.0 https://github.com/pgvector/pgvector.git /tmp/pgvector && \
    cd /tmp/pgvector && \
    make && make install && \
    rm -rf /tmp/pgvector