[project]
name = "fiap-datathon"
version = "0.1.0"
description = "Último projeto da Pós-Grad em Engenharia de Machine Learning"
readme = "README.md"
authors = [
  { name = "eng-alecrim", email = "lucasalecrimvieira@gmail.com" }
]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Intended Audience :: Science/Research",
]
dependencies = [
  "common",
  "core",
  "pip>=25.0.1",
]

[dependency-groups]
dev = [
  "black[jupyter]>=25.1.0",
  "pytest>=8.3.5",
  "pytest-cov>=6.1.1",
  "ipykernel>=6.29.5",
  "ipywidgets>=8.1.6",
  "taskipy>=1.14.1",
  "ruff>=0.11.5",
  "ignr>=2.2",

]

[tool.uv.sources]
core = { workspace = true }
common = { workspace = true }

[tool.uv.workspace]
members = ["src/packages/*"]

[tool.ruff]
line-length = 88
extend-exclude = ["migrations", "data"]

[tool.ruff.lint]
preview = true
select = ["I", "F", "E", "W", "PL", "PT"]
ignore = ["PLR1711", "E731"]

[tool.ruff.format]
preview = true
quote-style = "double"

[tool.pytest.ini_options]
pythonpath = "."
addopts = "-p no:warnings --cov=packages --cov-report=html:coverage_report -vv"
testpaths = ["tests"]

[tool.taskipy.tasks]
# Development workflow tasks
lint = "ruff check ."
format = "ruff format ."
test = "pytest"
cov = "pytest --cov=src/packages --cov-report=term-missing"
precommit = "task format && task lint && task test"




# Data processing tasks
process-bronze = "python -m core.data.bronze"
process-silver = "python -m core.data.silver"
process-gold = "python -m core.data.gold"


# Notebook conversion
nb-to-script = "jupyter nbconvert --to python src/notebooks/*.ipynb --output-dir=src/packages/core/scripts/"
