[project]
name = "fiap-datathon"
version = "0.1.0"
description = "Último projeto da Pós-Grad em Engenharia de Machine Learning"
readme = "README.md"
authors = [{ name = "eng-alecrim", email = "lucasalecrimvieira@gmail.com" }]
requires-python = ">=3.12"
dependencies = []

[tool.uv.sources]
common = { workspace = true }
custom_nlp = { workspace = true }

[tool.uv.workspace]
members = [
    "app/packages/*",
    "app/machine_learning",
    "app/database",
    "app/api",
]